SP500 = {'A.O. Smith Corp': 'AOS',
         'Abbott Laboratories': 'ABT',
         'AbbVie Inc.': 'ABBV',
         'Accenture plc': 'ACN',
         'Activision Blizzard': 'ATVI',
         'Acuity Brands Inc': 'AYI',
         'Adobe Systems Inc': 'ADBE',
         'Advance Auto Parts': 'AAP',
         'Advanced Micro Devices Inc': 'AMD',
         'AES Corp': 'AES',
         'Aetna Inc': 'AET',
         'Affiliated Managers Group Inc': 'AMG',
         'AFLAC Inc': 'AFL',
         'Agilent Technologies Inc': 'A',
         'Air Products & Chemicals Inc': 'APD',
         'Akamai Technologies Inc': 'AKAM',
         'Alaska Air Group Inc': 'ALK',
         'Albemarle Corp': 'ALB',
         'Alexandria Real Estate Equities Inc': 'ARE',
         'Alexion Pharmaceuticals': 'ALXN',
         'Align Technology': 'ALGN',
         'Allegion': 'ALLE',
         'Allergan, Plc': 'AGN',
         'Alliance Data Systems': 'ADS',
         'Alliant Energy Corp': 'LNT',
         'Allstate Corp': 'ALL',
         'Alphabet Inc Class A': 'GOOGL',
         'Alphabet Inc Class C': 'GOOG',
         'Altria Group Inc': 'MO',
         'Amazon.com Inc.': 'AMZN',
         'Ameren Corp': 'AEE',
         'American Airlines Group': 'AAL',
         'American Electric Power': 'AEP',
         'American Express Co': 'AXP',
         'American International Group, Inc.': 'AIG',
         'American Tower Corp A': 'AMT',
         'American Water Works Company Inc': 'AWK',
         'Ameriprise Financial': 'AMP',
         'AmerisourceBergen Corp': 'ABC',
         'AMETEK Inc.': 'AME',
         'Amgen Inc.': 'AMGN',
         'Amphenol Corp': 'APH',
         'Anadarko Petroleum Corp': 'APC',
         'Analog Devices, Inc.': 'ADI',
         'Andeavor': 'ANDV',
         'ANSYS': 'ANSS',
         'Anthem Inc.': 'ANTM',
         'Aon plc': 'AON',
         'Apache Corporation': 'APA',
         'Apartment Investment & Management': 'AIV',
         'Apple Inc.': 'AAPL',
         'Applied Materials Inc.': 'AMAT',
         'Aptiv Plc': 'APTV',
         'Archer-Daniels-Midland Co': 'ADM',
         'Arconic Inc.': 'ARNC',
         'Arthur J. Gallagher & Co.': 'AJG',
         'Assurant Inc.': 'AIZ',
         'AT&T Inc.': 'T',
         'Autodesk Inc.': 'ADSK',
         'Automatic Data Processing': 'ADP',
         'AutoZone Inc': 'AZO',
         'AvalonBay Communities, Inc.': 'AVB',
         'Avery Dennison Corp': 'AVY',
         'Baker Hughes, a GE Company': 'BHGE',
         'Ball Corp': 'BLL',
         'Bank of America Corp': 'BAC',
         'Baxter International Inc.': 'BAX',
         'BB&T Corporation': 'BBT',
         'Becton Dickinson': 'BDX',
         'Berkshire Hathaway': 'BRK_A',
         'Best Buy Co. Inc.': 'BBY',
         'Biogen Inc.': 'BIIB',
         'BlackRock': 'BLK',
         'Block H&R': 'HRB',
         'Boeing Company': 'BA',
         'Booking Holdings Inc': 'BKNG',
         'BorgWarner': 'BWA',
         'Boston Properties': 'BXP',
         'Boston Scientific': 'BSX',
         'Brighthouse Financial Inc': 'BHF',
         'Bristol-Myers Squibb': 'BMY',
         'Broadcom': 'AVGO',
         'Brown-Forman Corp.': 'BF_B',
         'C. H. Robinson Worldwide': 'CHRW',
         'CA, Inc.': 'CA',
         'Cabot Oil & Gas': 'COG',
         'Cadence Design Systems': 'CDNS',
         'Campbell Soup': 'CPB',
         'Capital One Financial': 'COF',
         'Cardinal Health Inc.': 'CAH',
         'Carmax Inc': 'KMX',
         'Carnival Corp.': 'CCL',
         'Caterpillar Inc.': 'CAT',
         'Cboe Global Markets': 'CBOE',
         'CBRE Group': 'CBRE',
         'CBS Corp.': 'CBS',
         'Celgene Corp.': 'CELG',
         'Centene Corporation': 'CNC',
         'CenterPoint Energy': 'CNP',
         'CenturyLink Inc': 'CTL',
         'Cerner': 'CERN',
         'CF Industries Holdings Inc': 'CF',
         'Charles Schwab Corporation': 'SCHW',
         'Charter Communications': 'CHTR',
         'Chevron Corp.': 'CVX',
         'Chipotle Mexican Grill': 'CMG',
         'Chubb Limited': 'CB',
         'Church & Dwight': 'CHD',
         'CIGNA Corp.': 'CI',
         'Cimarex Energy': 'XEC',
         'Cincinnati Financial': 'CINF',
         'Cintas Corporation': 'CTAS',
         'Cisco Systems': 'CSCO',
         'Citigroup Inc.': 'C',
         'Citizens Financial Group': 'CFG',
         'Citrix Systems': 'CTXS',
         'CME Group Inc.': 'CME',
         'CMS Energy': 'CMS',
         'Coca-Cola Company (The)': 'KO',
         'Cognizant Technology Solutions': 'CTSH',
         'Colgate-Palmolive': 'CL',
         'Comcast Corp.': 'CMCSA',
         'Comerica Inc.': 'CMA',
         'Conagra Brands': 'CAG',
         'Concho Resources': 'CXO',
         'ConocoPhillips': 'COP',
         'Consolidated Edison': 'ED',
         'Constellation Brands': 'STZ',
         'Corning Inc.': 'GLW',
         'Costco Wholesale Corp.': 'COST',
         'Coty, Inc': 'COTY',
         'Crown Castle International Corp.': 'CCI',
         'CSRA Inc.': 'CSRA',
         'CSX Corp.': 'CSX',
         'Cummins Inc.': 'CMI',
         'CVS Health': 'CVS',
         'D. R. Horton': 'DHI',
         'Danaher Corp.': 'DHR',
         'Darden Restaurants': 'DRI',
         'DaVita Inc.': 'DVA',
         'Deere & Co.': 'DE',
         'Delta Air Lines Inc.': 'DAL',
         'Dentsply Sirona': 'XRAY',
         'Devon Energy Corp.': 'DVN',
         'Digital Realty Trust Inc': 'DLR',
         'Discover Financial Services': 'DFS',
         'Discovery Inc. Class A': 'DISCA',
         'Discovery Inc. Class C': 'DISCK',
         'Dish Network': 'DISH',
         'Dollar General': 'DG',
         'Dollar Tree': 'DLTR',
         'Dominion Energy': 'D',
         'Dover Corp.': 'DOV',
         'DowDuPont': 'DWDP',
         'Dr Pepper Snapple Group': 'DPS',
         'DTE Energy Co.': 'DTE',
         'Duke Energy': 'DUK',
         'Duke Realty Corp': 'DRE',
         'DXC Technology': 'DXC',
         'E*Trade': 'ETFC',
         'Eastman Chemical': 'EMN',
         'Eaton Corporation': 'ETN',
         'eBay Inc.': 'EBAY',
         'Ecolab Inc.': 'ECL',
         'Edison International': 'EIX',
         'Edwards Lifesciences': 'EW',
         'Electronic Arts': 'EA',
         'Emerson Electric Company': 'EMR',
         'Entergy Corp.': 'ETR',
         'Envision Healthcare': 'EVHC',
         'EOG Resources': 'EOG',
         'EQT Corporation': 'EQT',
         'Equifax Inc.': 'EFX',
         'Equinix': 'EQIX',
         'Equity Residential': 'EQR',
         'Essex Property Trust, Inc.': 'ESS',
         'Estee Lauder Cos.': 'EL',
         'Everest Re Group Ltd.': 'RE',
         'Eversource Energy': 'ES',
         'Exelon Corp.': 'EXC',
         'Expedia Inc.': 'EXPE',
         'Expeditors International': 'EXPD',
         'Express Scripts': 'ESRX',
         'Extra Space Storage': 'EXR',
         'Exxon Mobil Corp.': 'XOM',
         'F5 Networks': 'FFIV',
         'Facebook, Inc.': 'FB',
         'Fastenal Co': 'FAST',
         'Federal Realty Investment Trust': 'FRT',
         'FedEx Corporation': 'FDX',
         'Fidelity National Information Services': 'FIS',
         'Fifth Third Bancorp': 'FITB',
         'FirstEnergy Corp': 'FE',
         'Fiserv Inc': 'FISV',
         'FLIR Systems': 'FLIR',
         'Flowserve Corporation': 'FLS',
         'Fluor Corp.': 'FLR',
         'FMC Corporation': 'FMC',
         'Foot Locker Inc': 'FL',
         'Ford Motor': 'F',
         'Fortive Corp': 'FTV',
         'Fortune Brands Home & Security': 'FBHS',
         'Franklin Resources': 'BEN',
         'Freeport-McMoRan Inc.': 'FCX',
         'Gap Inc.': 'GPS',
         'Garmin Ltd.': 'GRMN',
         'Gartner Inc': 'IT',
         'General Dynamics': 'GD',
         'General Electric': 'GE',
         'General Growth Properties Inc.': 'GGP',
         'General Mills': 'GIS',
         'General Motors': 'GM',
         'Genuine Parts': 'GPC',
         'Gilead Sciences': 'GILD',
         'Global Payments Inc.': 'GPN',
         'Goldman Sachs Group': 'GS',
         'Goodyear Tire & Rubber': 'GT',
         'Grainger (W.W.) Inc.': 'GWW',
         'Halliburton Co.': 'HAL',
         'Hanesbrands Inc': 'HBI',
         'Harley-Davidson': 'HOG',
         'Harris Corporation': 'HRS',
         'Hartford Financial Svc.Gp.': 'HIG',
         'Hasbro Inc.': 'HAS',
         'HCA Holdings': 'HCA',
         'HCP Inc.': 'HCP',
         'Helmerich & Payne': 'HP',
         'Henry Schein': 'HSIC',
         'Hess Corporation': 'HES',
         'Hewlett Packard Enterprise': 'HPE',
         'Hilton Worldwide Holdings Inc': 'HLT',
         'Hologic': 'HOLX',
         'Home Depot': 'HD',
         'Honeywell International Inc.': 'HON',
         'Hormel Foods Corp.': 'HRL',
         'Host Hotels & Resorts': 'HST',
         'HP Inc.': 'HPQ',
         'Humana Inc.': 'HUM',
         'Huntington Bancshares': 'HBAN',
         'Huntington Ingalls Industries': 'HII',
         'IDEXX Laboratories': 'IDXX',
         'IHS Markit Ltd.': 'INFO',
         'Illinois Tool Works': 'ITW',
         'Illumina Inc': 'ILMN',
         'Incyte': 'INCY',
         'Ingersoll-Rand PLC': 'IR',
         'Intel Corp.': 'INTC',
         'Intercontinental Exchange': 'ICE',
         'International Business Machines': 'IBM',
         'International Paper': 'IP',
         'Interpublic Group': 'IPG',
         'Intl Flavors & Fragrances': 'IFF',
         'Intuit Inc.': 'INTU',
         'Intuitive Surgical Inc.': 'ISRG',
         'Invesco Ltd.': 'IVZ',
         'IPG Photonics Corp.': 'IPGP',
         'IQVIA Holdings Inc.': 'IQV',
         'Iron Mountain Incorporated': 'IRM',
         'J. B. Hunt Transport Services': 'JBHT',
         'Jacobs Engineering Group': 'JEC',
         'JM Smucker': 'SJM',
         'Johnson & Johnson': 'JNJ',
         'Johnson Controls International': 'JCI',
         'JPMorgan Chase & Co.': 'JPM',
         'Juniper Networks': 'JNPR',
         'Kansas City Southern': 'KSU',
         'Kellogg Co.': 'K',
         'KeyCorp': 'KEY',
         'Kimberly-Clark': 'KMB',
         'Kimco Realty': 'KIM',
         'Kinder Morgan': 'KMI',
         'KLA-Tencor Corp.': 'KLAC',
         'Kohls Corp.': 'KSS',
         'Kraft Heinz Co': 'KHC',
         'Kroger Co.': 'KR',
         'L Brands Inc.': 'LB',
         'L-3 Communications Holdings': 'LLL',
         'Laboratory Corp. of America Holding': 'LH',
         'Lam Research': 'LRCX',
         'Leggett & Platt': 'LEG',
         'Lennar Corp.': 'LEN',
         'Leucadia National Corp.': 'LUK',
         'Lilly (Eli) & Co.': 'LLY',
         'Lincoln National': 'LNC',
         'LKQ Corporation': 'LKQ',
         'Lockheed Martin Corp.': 'LMT',
         'Loews Corp.': 'L',
         'Lowes Cos.': 'LOW',
         'LyondellBasell': 'LYB',
         'M&T Bank Corp.': 'MTB',
         'Macerich': 'MAC',
         'Macys Inc.': 'M',
         'Marathon Oil Corp.': 'MRO',
         'Marathon Petroleum': 'MPC',
         'Marriott International.': 'MAR',
         'Marsh & McLennan': 'MMC',
         'Martin Marietta Materials': 'MLM',
         'Masco Corp.': 'MAS',
         'Mastercard Inc.': 'MA',
         'Mattel Inc.': 'MAT',
         'McCormick & Co.': 'MKC',
         'McDonalds Corp.': 'MCD',
         'McKesson Corp.': 'MCK',
         'Medtronic plc': 'MDT',
         'Merck & Co.': 'MRK',
         'MetLife Inc.': 'MET',
         'Mettler Toledo': 'MTD',
         'MGM Resorts International': 'MGM',
         'Michael Kors Holdings': 'KORS',
         'Microchip Technology': 'MCHP',
         'Micron Technology': 'MU',
         'Microsoft Corp.': 'MSFT',
         'Mid-America Apartments': 'MAA',
         'Mohawk Industries': 'MHK',
         'Molson Coors Brewing Company': 'TAP',
         'Mondelez International': 'MDLZ',
         'Monsanto Co.': 'MON',
         'Monster Beverage': 'MNST',
         'Moodys Corp': 'MCO',
         'Morgan Stanley': 'MS',
         'Motorola Solutions Inc.': 'MSI',
         'Mylan N.V.': 'MYL',
         'Nasdaq, Inc.': 'NDAQ',
         'National Oilwell Varco Inc.': 'NOV',
         'Navient': 'NAVI',
         'Nektar Therapeutics': 'NKTR',
         'NetApp': 'NTAP',
         'Netflix Inc.': 'NFLX',
         'Newell Brands': 'NWL',
         'Newfield Exploration Co': 'NFX',
         'Newmont Mining Corporation': 'NEM',
         'News Corp. Class A': 'NWSA',
         'News Corp. Class B': 'NWS',
         'NextEra Energy': 'NEE',
         'Nielsen Holdings': 'NLSN',
         'Nike': 'NKE',
         'NiSource Inc.': 'NI',
         'Noble Energy Inc': 'NBL',
         'Nordstrom': 'JWN',
         'Norfolk Southern Corp.': 'NSC',
         'Northern Trust Corp.': 'NTRS',
         'Northrop Grumman Corp.': 'NOC',
         'Norwegian Cruise Line': 'NCLH',
         'NRG Energy': 'NRG',
         'Nucor Corp.': 'NUE',
         'Nvidia Corporation': 'NVDA',
         'OReilly Automotive': 'ORLY',
         'Occidental Petroleum': 'OXY',
         'Omnicom Group': 'OMC',
         'ONEOK': 'OKE',
         'Oracle Corp.': 'ORCL',
         'PACCAR Inc.': 'PCAR',
         'Packaging Corporation of America': 'PKG',
         'Parker-Hannifin': 'PH',
         'Paychex Inc.': 'PAYX',
         'PayPal': 'PYPL',
         'Pentair Ltd.': 'PNR',
         'Peoples United Financial': 'PBCT',
         'PepsiCo Inc.': 'PEP',
         'PerkinElmer': 'PKI',
         'Perrigo': 'PRGO',
         'Pfizer Inc.': 'PFE',
         'PG&E Corp.': 'PCG',
         'Philip Morris International': 'PM',
         'Phillips 66': 'PSX',
         'Pinnacle West Capital': 'PNW',
         'Pioneer Natural Resources': 'PXD',
         'PNC Financial Services': 'PNC',
         'Polo Ralph Lauren Corp.': 'RL',
         'PPG Industries': 'PPG',
         'PPL Corp.': 'PPL',
         'Praxair Inc.': 'PX',
         'Principal Financial Group': 'PFG',
         'Procter & Gamble': 'PG',
         'Progressive Corp.': 'PGR',
         'Prologis': 'PLD',
         'Prudential Financial': 'PRU',
         'Public Serv. Enterprise Inc.': 'PEG',
         'Public Storage': 'PSA',
         'Pulte Homes Inc.': 'PHM',
         'PVH Corp.': 'PVH',
         'Qorvo': 'QRVO',
         'QUALCOMM Inc.': 'QCOM',
         'Quanta Services Inc.': 'PWR',
         'Quest Diagnostics': 'DGX',
         'Range Resources Corp.': 'RRC',
         'Raymond James Financial Inc.': 'RJF',
         'Raytheon Co.': 'RTN',
         'Realty Income Corporation': 'O',
         'Red Hat Inc.': 'RHT',
         'Regency Centers Corporation': 'REG',
         'Regeneron': 'REGN',
         'Regions Financial Corp.': 'RF',
         'Republic Services Inc': 'RSG',
         'ResMed': 'RMD',
         'Robert Half International': 'RHI',
         'Rockwell Automation Inc.': 'ROK',
         'Rockwell Collins': 'COL',
         'Roper Technologies': 'ROP',
         'Ross Stores': 'ROST',
         'Royal Caribbean Cruises Ltd': 'RCL',
         'S&P Global, Inc.': 'SPGI',
         'Salesforce.com': 'CRM',
         'SBA Communications': 'SBAC',
         'SCANA Corp': 'SCG',
         'Schlumberger Ltd.': 'SLB',
         'Seagate Technology': 'STX',
         'Sealed Air': 'SEE',
         'Sempra Energy': 'SRE',
         'Sherwin-Williams': 'SHW',
         'Simon Property Group Inc': 'SPG',
         'Skyworks Solutions': 'SWKS',
         'SL Green Realty': 'SLG',
         'Snap-On Inc.': 'SNA',
         'Southern Co.': 'SO',
         'Southwest Airlines': 'LUV',
         'Stanley Black & Decker': 'SWK',
         'Starbucks Corp.': 'SBUX',
         'State Street Corp.': 'STT',
         'Stericycle Inc': 'SRCL',
         'Stryker Corp.': 'SYK',
         'SunTrust Banks': 'STI',
         'SVB Financial': 'SIVB',
         'Symantec Corp.': 'SYMC',
         'Synchrony Financial': 'SYF',
         'Synopsys Inc.': 'SNPS',
         'Sysco Corp.': 'SYY',
         'T. Rowe Price Group': 'TROW',
         'Take-Two Interactive': 'TTWO',
         'Tapestry, Inc.': 'TPR',
         'Target Corp.': 'TGT',
         'TE Connectivity Ltd.': 'TEL',
         'TechnipFMC': 'FTI',
         'Texas Instruments': 'TXN',
         'Textron Inc.': 'TXT',
         'The Bank of New York Mellon Corp.': 'BK',
         'The Clorox Company': 'CLX',
         'The Cooper Companies': 'COO',
         'The Hershey Company': 'HSY',
         'The Mosaic Company': 'MOS',
         'The Travelers Companies Inc.': 'TRV',
         'The Walt Disney Company': 'DIS',
         'Thermo Fisher Scientific': 'TMO',
         'Tiffany & Co.': 'TIF',
         'Time Warner Inc.': 'TWX',
         'TJX Companies Inc.': 'TJX',
         'Torchmark Corp.': 'TMK',
         'Total System Services': 'TSS',
         'Tractor Supply Company': 'TSCO',
         'TransDigm Group': 'TDG',
         'TripAdvisor': 'TRIP',
         'Twenty-First Century Fox Class A': 'FOXA',
         'Twenty-First Century Fox Class B': 'FOX',
         'Tyson Foods': 'TSN',
         'U.S. Bancorp': 'USB',
         'UDR Inc': 'UDR',
         'Ulta Beauty': 'ULTA',
         'Under Armour Class A': 'UAA',
         'Under Armour Class C': 'UA',
         'Union Pacific': 'UNP',
         'United Continental Holdings': 'UAL',
         'United Health Group Inc.': 'UNH',
         'United Parcel Service': 'UPS',
         'United Rentals, Inc.': 'URI',
         'United Technologies': 'UTX',
         'Universal Health Services, Inc.': 'UHS',
         'Unum Group': 'UNM',
         'V.F. Corp.': 'VFC',
         'Valero Energy': 'VLO',
         'Varian Medical Systems': 'VAR',
         'Ventas Inc': 'VTR',
         'Verisign Inc.': 'VRSN',
         'Verisk Analytics': 'VRSK',
         'Verizon Communications': 'VZ',
         'Vertex Pharmaceuticals Inc': 'VRTX',
         'Viacom Inc.': 'VIAB',
         'Visa Inc.': 'V',
         'Vornado Realty Trust': 'VNO',
         'Vulcan Materials': 'VMC',
         'Wal-Mart Stores': 'WMT',
         'Walgreens Boots Alliance': 'WBA',
         'Waste Management Inc.': 'WM',
         'Waters Corporation': 'WAT',
         'Wec Energy Group Inc': 'WEC',
         'Wells Fargo': 'WFC',
         'Welltower Inc.': 'WELL',
         'Western Digital': 'WDC',
         'Western Union Co': 'WU',
         'WestRock Company': 'WRK',
         'Weyerhaeuser Corp.': 'WY',
         'Whirlpool Corp.': 'WHR',
         'Williams Cos.': 'WMB',
         'Willis Towers Watson': 'WLTW',
         'Wyndham Worldwide': 'WYN',
         'Wynn Resorts Ltd': 'WYNN',
         'Xcel Energy Inc': 'XEL',
         'Xerox Corp.': 'XRX',
         'Xilinx Inc': 'XLNX',
         'XL Capital': 'XL',
         'Xylem Inc.': 'XYL',
         'Yum! Brands Inc': 'YUM',
         'Zimmer Biomet Holdings': 'ZBH',
         'Zions Bancorp': 'ZION',
         'Zoetis': 'ZTS'}



ISO3 = {'Afghanistan': 'AFG',
        'Åland Islands': 'ALA',
        'Albania': 'ALB',
        'Algeria': 'DZA',
        'American Samoa': 'ASM',
        'Andorra': 'AND',
        'Angola': 'AGO',
        'Anguilla': 'AIA',
        'Antarctica': 'ATA',
        'Antigua and Barbuda': 'ATG',
        'Argentina': 'ARG',
        'Armenia': 'ARM',
        'Aruba': 'ABW',
        'Australia': 'AUS',
        'Austria': 'AUT',
        'Azerbaijan': 'AZE',
        'Bahamas': 'BHS',
        'Bahrain': 'BHR',
        'Bangladesh': 'BGD',
        'Barbados': 'BRB',
        'Belarus': 'BLR',
        'Belgium': 'BEL',
        'Belize': 'BLZ',
        'Benin': 'BEN',
        'Bermuda': 'BMU',
        'Bhutan': 'BTN',
        'Bolivia, Plurinational State of': 'BOL',
        'Bonaire, Sint Eustatius and Saba': 'BES',
        'Bosnia and Herzegovina': 'BIH',
        'Botswana': 'BWA',
        'Bouvet Island': 'BVT',
        'Brazil': 'BRA',
        'British Indian Ocean Territory': 'IOT',
        'Brunei Darussalam': 'BRN',
        'Bulgaria': 'BGR',
        'Burkina Faso': 'BFA',
        'Burundi': 'BDI',
        'Cambodia': 'KHM',
        'Cameroon': 'CMR',
        'Canada': 'CAN',
        'Cape Verde': 'CPV',
        'Cayman Islands': 'CYM',
        'Central African Republic': 'CAF',
        'Chad': 'TCD',
        'Chile': 'CHL',
        'China': 'CHN',
        'Christmas Island': 'CXR',
        'Cocos (Keeling) Islands': 'CCK',
        'Colombia': 'COL',
        'Comoros': 'COM',
        'Congo': 'COG',
        'Congo, the Democratic Republic of the': 'COD',
        'Cook Islands': 'COK',
        'Costa Rica': 'CRI',
        'Côte dIvoire': 'CIV',
        'Croatia': 'HRV',
        'Cuba': 'CUB',
        'Curaçao': 'CUW',
        'Cyprus': 'CYP',
        'Czech Republic': 'CZE',
        'Denmark': 'DNK',
        'Djibouti': 'DJI',
        'Dominica': 'DMA',
        'Dominican Republic': 'DOM',
        'Ecuador': 'ECU',
        'Egypt': 'EGY',
        'El Salvador': 'SLV',
        'Equatorial Guinea': 'GNQ',
        'Eritrea': 'ERI',
        'Estonia': 'EST',
        'Ethiopia': 'ETH',
        'Falkland Islands (Malvinas)': 'FLK',
        'Faroe Islands': 'FRO',
        'Fiji': 'FJI',
        'Finland': 'FIN',
        'France': 'FRA',
        'French Guiana': 'GUF',
        'French Polynesia': 'PYF',
        'French Southern Territories': 'ATF',
        'Gabon': 'GAB',
        'Gambia': 'GMB',
        'Georgia': 'GEO',
        'Germany': 'DEU',
        'Ghana': 'GHA',
        'Gibraltar': 'GIB',
        'Greece': 'GRC',
        'Greenland': 'GRL',
        'Grenada': 'GRD',
        'Guadeloupe': 'GLP',
        'Guam': 'GUM',
        'Guatemala': 'GTM',
        'Guernsey': 'GGY',
        'Guinea': 'GIN',
        'Guinea-Bissau': 'GNB',
        'Guyana': 'GUY',
        'Haiti': 'HTI',
        'Heard Island and McDonald Islands': 'HMD',
        'Holy See (Vatican City State)': 'VAT',
        'Honduras': 'HND',
        'Hong Kong': 'HKG',
        'Hungary': 'HUN',
        'Iceland': 'ISL',
        'India': 'IND',
        'Indonesia': 'IDN',
        'Iran, Islamic Republic of': 'IRN',
        'Iraq': 'IRQ',
        'Ireland': 'IRL',
        'Isle of Man': 'IMN',
        'Israel': 'ISR',
        'Italy': 'ITA',
        'Jamaica': 'JAM',
        'Japan': 'JPN',
        'Jersey': 'JEY',
        'Jordan': 'JOR',
        'Kazakhstan': 'KAZ',
        'Kenya': 'KEN',
        'Kiribati': 'KIR',
        'Korea, Democratic Peoples Republic of': 'PRK',
        'Korea, Republic of': 'KOR',
        'Kuwait': 'KWT',
        'Kyrgyzstan': 'KGZ',
        'Lao Peoples Democratic Republic': 'LAO',
        'Latvia': 'LVA',
        'Lebanon': 'LBN',
        'Lesotho': 'LSO',
        'Liberia': 'LBR',
        'Libya': 'LBY',
        'Liechtenstein': 'LIE',
        'Lithuania': 'LTU',
        'Luxembourg': 'LUX',
        'Macao': 'MAC',
        'Macedonia, the former Yugoslav Republic of': 'MKD',
        'Madagascar': 'MDG',
        'Malawi': 'MWI',
        'Malaysia': 'MYS',
        'Maldives': 'MDV',
        'Mali': 'MLI',
        'Malta': 'MLT',
        'Marshall Islands': 'MHL',
        'Martinique': 'MTQ',
        'Mauritania': 'MRT',
        'Mauritius': 'MUS',
        'Mayotte': 'MYT',
        'Mexico': 'MEX',
        'Micronesia, Federated States of': 'FSM',
        'Moldova, Republic of': 'MDA',
        'Monaco': 'MCO',
        'Mongolia': 'MNG',
        'Montenegro': 'MNE',
        'Montserrat': 'MSR',
        'Morocco': 'MAR',
        'Mozambique': 'MOZ',
        'Myanmar': 'MMR',
        'Namibia': 'NAM',
        'Nauru': 'NRU',
        'Nepal': 'NPL',
        'Netherlands': 'NLD',
        'New Caledonia': 'NCL',
        'New Zealand': 'NZL',
        'Nicaragua': 'NIC',
        'Niger': 'NER',
        'Nigeria': 'NGA',
        'Niue': 'NIU',
        'Norfolk Island': 'NFK',
        'Northern Mariana Islands': 'MNP',
        'Norway': 'NOR',
        'Oman': 'OMN',
        'Pakistan': 'PAK',
        'Palau': 'PLW',
        'Palestine, State of': 'PSE',
        'Panama': 'PAN',
        'Papua New Guinea': 'PNG',
        'Paraguay': 'PRY',
        'Peru': 'PER',
        'Philippines': 'PHL',
        'Pitcairn': 'PCN',
        'Poland': 'POL',
        'Portugal': 'PRT',
        'Puerto Rico': 'PRI',
        'Qatar': 'QAT',
        'Réunion': 'REU',
        'Romania': 'ROU',
        'Russian Federation': 'RUS',
        'Rwanda': 'RWA',
        'Saint Barthélemy': 'BLM',
        'Saint Helena, Ascension and Tristan da Cunha': 'SHN',
        'Saint Kitts and Nevis': 'KNA',
        'Saint Lucia': 'LCA',
        'Saint Martin (French part)': 'MAF',
        'Saint Pierre and Miquelon': 'SPM',
        'Saint Vincent and the Grenadines': 'VCT',
        'Samoa': 'WSM',
        'San Marino': 'SMR',
        'Sao Tome and Principe': 'STP',
        'Saudi Arabia': 'SAU',
        'Senegal': 'SEN',
        'Serbia': 'SRB',
        'Seychelles': 'SYC',
        'Sierra Leone': 'SLE',
        'Singapore': 'SGP',
        'Sint Maarten (Dutch part)': 'SXM',
        'Slovakia': 'SVK',
        'Slovenia': 'SVN',
        'Solomon Islands': 'SLB',
        'Somalia': 'SOM',
        'South Africa': 'ZAF',
        'South Georgia and the South Sandwich Islands': 'SGS',
        'South Sudan': 'SSD',
        'Spain': 'ESP',
        'Sri Lanka': 'LKA',
        'Sudan': 'SDN',
        'Suriname': 'SUR',
        'Svalbard and Jan Mayen': 'SJM',
        'Swaziland': 'SWZ',
        'Sweden': 'SWE',
        'Switzerland': 'CHE',
        'Syrian Arab Republic': 'SYR',
        'Taiwan, Province of China': 'TWN',
        'Tajikistan': 'TJK',
        'Tanzania, United Republic of': 'TZA',
        'Thailand': 'THA',
        'Timor-Leste': 'TLS',
        'Togo': 'TGO',
        'Tokelau': 'TKL',
        'Tonga': 'TON',
        'Trinidad and Tobago': 'TTO',
        'Tunisia': 'TUN',
        'Turkey': 'TUR',
        'Turkmenistan': 'TKM',
        'Turks and Caicos Islands': 'TCA',
        'Tuvalu': 'TUV',
        'Uganda': 'UGA',
        'Ukraine': 'UKR',
        'United Arab Emirates': 'ARE',
        'United Kingdom': 'GBR',
        'United States': 'USA',
        'United States Minor Outlying Islands': 'UMI',
        'Uruguay': 'URY',
        'Uzbekistan': 'UZB',
        'Vanuatu': 'VUT',
        'Venezuela, Bolivarian Republic of': 'VEN',
        'Viet Nam': 'VNM',
        'Virgin Islands, British': 'VGB',
        'Virgin Islands, U.S.': 'VIR',
        'Wallis and Futuna': 'WLF',
        'Western Sahara': 'ESH',
        'Yemen': 'YEM',
        'Zambia': 'ZMB',
        'Zimbabwe': 'ZWE'}